// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuL4C-3iVMUJKG9rfFUGijwBuTQyIrMDQ',
    appId: '1:768498679706:web:aad653e27673e871ec8423',
    messagingSenderId: '768498679706',
    projectId: 'fir-demo-bdc9b',
    authDomain: 'fir-demo-bdc9b.firebaseapp.com',
    storageBucket: 'fir-demo-bdc9b.firebasestorage.app',
    measurementId: 'G-Z4HERR95R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCLc44wqi6tKYOP4dFNUO1zKD4XPCacM',
    appId: '1:768498679706:android:dc4969facfe8c043ec8423',
    messagingSenderId: '768498679706',
    projectId: 'fir-demo-bdc9b',
    storageBucket: 'fir-demo-bdc9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Vy1FX58LAdtHFff0dxdi1NqpfroAxYM',
    appId: '1:768498679706:ios:4aa09d864f42dd53ec8423',
    messagingSenderId: '768498679706',
    projectId: 'fir-demo-bdc9b',
    storageBucket: 'fir-demo-bdc9b.firebasestorage.app',
    iosBundleId: 'com.example.abcBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Vy1FX58LAdtHFff0dxdi1NqpfroAxYM',
    appId: '1:768498679706:ios:4aa09d864f42dd53ec8423',
    messagingSenderId: '768498679706',
    projectId: 'fir-demo-bdc9b',
    storageBucket: 'fir-demo-bdc9b.firebasestorage.app',
    iosBundleId: 'com.example.abcBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuL4C-3iVMUJKG9rfFUGijwBuTQyIrMDQ',
    appId: '1:768498679706:web:e8060f98a5da943fec8423',
    messagingSenderId: '768498679706',
    projectId: 'fir-demo-bdc9b',
    authDomain: 'fir-demo-bdc9b.firebaseapp.com',
    storageBucket: 'fir-demo-bdc9b.firebasestorage.app',
    measurementId: 'G-RDN9B00QSX',
  );
}
